CREATE SCHEMA `CANDOIT_EJ`;

CREATE TABLE `ALUMNO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(255) NOT NULL,
  `APELLIDO` VARCHAR(255) NOT NULL,
  `DNI` BIGINT UNSIGNED NOT NULL,
  `FECHA_NACIMIENTO` TIMESTAMP NOT NULL,
  `FECHA_ALTA` TIMESTAMP NOT NULL,
  `FECHA_BAJA` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `CURSO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(255) NULL,
  `FECHA_ALTA` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `ALUMNO_CURSO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ID_CURSO` BIGINT NOT NULL,
  `ID_ALUMNO` BIGINT NOT NULL,
  `FECHA_ALTA` TIMESTAMP NULL,
  PRIMARY KEY (`ID`));